// Generated by gencpp from file path_planner/CreateGraph.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_CREATEGRAPH_H
#define PATH_PLANNER_MESSAGE_CREATEGRAPH_H

#include <ros/service_traits.h>


#include <path_planner/CreateGraphRequest.h>
#include <path_planner/CreateGraphResponse.h>


namespace path_planner
{

struct CreateGraph
{

typedef CreateGraphRequest Request;
typedef CreateGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreateGraph
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::CreateGraph > {
  static const char* value()
  {
    return "f5d270e8ce37df345157a107cd8c1f39";
  }

  static const char* value(const ::path_planner::CreateGraph&) { return value(); }
};

template<>
struct DataType< ::path_planner::CreateGraph > {
  static const char* value()
  {
    return "path_planner/CreateGraph";
  }

  static const char* value(const ::path_planner::CreateGraph&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::CreateGraphRequest> should match 
// service_traits::MD5Sum< ::path_planner::CreateGraph > 
template<>
struct MD5Sum< ::path_planner::CreateGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::CreateGraph >::value();
  }
  static const char* value(const ::path_planner::CreateGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::CreateGraphRequest> should match 
// service_traits::DataType< ::path_planner::CreateGraph > 
template<>
struct DataType< ::path_planner::CreateGraphRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::CreateGraph >::value();
  }
  static const char* value(const ::path_planner::CreateGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::CreateGraphResponse> should match 
// service_traits::MD5Sum< ::path_planner::CreateGraph > 
template<>
struct MD5Sum< ::path_planner::CreateGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::CreateGraph >::value();
  }
  static const char* value(const ::path_planner::CreateGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::CreateGraphResponse> should match 
// service_traits::DataType< ::path_planner::CreateGraph > 
template<>
struct DataType< ::path_planner::CreateGraphResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::CreateGraph >::value();
  }
  static const char* value(const ::path_planner::CreateGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_CREATEGRAPH_H
