// Generated by gencpp from file path_planner/CreateGraphRequest.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_CREATEGRAPHREQUEST_H
#define PATH_PLANNER_MESSAGE_CREATEGRAPHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planner
{
template <class ContainerAllocator>
struct CreateGraphRequest_
{
  typedef CreateGraphRequest_<ContainerAllocator> Type;

  CreateGraphRequest_()
    : map_id()
    , roadmap_growth_time(0)
    , roadmap_expansion_time(0)  {
    }
  CreateGraphRequest_(const ContainerAllocator& _alloc)
    : map_id(_alloc)
    , roadmap_growth_time(0)
    , roadmap_expansion_time(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_id_type;
  _map_id_type map_id;

   typedef int8_t _roadmap_growth_time_type;
  _roadmap_growth_time_type roadmap_growth_time;

   typedef int8_t _roadmap_expansion_time_type;
  _roadmap_expansion_time_type roadmap_expansion_time;





  typedef boost::shared_ptr< ::path_planner::CreateGraphRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::CreateGraphRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CreateGraphRequest_

typedef ::path_planner::CreateGraphRequest_<std::allocator<void> > CreateGraphRequest;

typedef boost::shared_ptr< ::path_planner::CreateGraphRequest > CreateGraphRequestPtr;
typedef boost::shared_ptr< ::path_planner::CreateGraphRequest const> CreateGraphRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::CreateGraphRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::CreateGraphRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::CreateGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::CreateGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::CreateGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db2531742554cd58a335cb0b94ae809f";
  }

  static const char* value(const ::path_planner::CreateGraphRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb2531742554cd58ULL;
  static const uint64_t static_value2 = 0xa335cb0b94ae809fULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/CreateGraphRequest";
  }

  static const char* value(const ::path_planner::CreateGraphRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_id\n\
int8 roadmap_growth_time\n\
int8 roadmap_expansion_time\n\
";
  }

  static const char* value(const ::path_planner::CreateGraphRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_id);
      stream.next(m.roadmap_growth_time);
      stream.next(m.roadmap_expansion_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreateGraphRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::CreateGraphRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::CreateGraphRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_id);
    s << indent << "roadmap_growth_time: ";
    Printer<int8_t>::stream(s, indent + "  ", v.roadmap_growth_time);
    s << indent << "roadmap_expansion_time: ";
    Printer<int8_t>::stream(s, indent + "  ", v.roadmap_expansion_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_CREATEGRAPHREQUEST_H
