// Generated by gencpp from file path_planner/FindPath.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_FINDPATH_H
#define PATH_PLANNER_MESSAGE_FINDPATH_H

#include <ros/service_traits.h>


#include <path_planner/FindPathRequest.h>
#include <path_planner/FindPathResponse.h>


namespace path_planner
{

struct FindPath
{

typedef FindPathRequest Request;
typedef FindPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindPath
} // namespace path_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_planner::FindPath > {
  static const char* value()
  {
    return "fbf4be726dfae8f25934ac5e341e5c84";
  }

  static const char* value(const ::path_planner::FindPath&) { return value(); }
};

template<>
struct DataType< ::path_planner::FindPath > {
  static const char* value()
  {
    return "path_planner/FindPath";
  }

  static const char* value(const ::path_planner::FindPath&) { return value(); }
};


// service_traits::MD5Sum< ::path_planner::FindPathRequest> should match 
// service_traits::MD5Sum< ::path_planner::FindPath > 
template<>
struct MD5Sum< ::path_planner::FindPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::FindPath >::value();
  }
  static const char* value(const ::path_planner::FindPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::FindPathRequest> should match 
// service_traits::DataType< ::path_planner::FindPath > 
template<>
struct DataType< ::path_planner::FindPathRequest>
{
  static const char* value()
  {
    return DataType< ::path_planner::FindPath >::value();
  }
  static const char* value(const ::path_planner::FindPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_planner::FindPathResponse> should match 
// service_traits::MD5Sum< ::path_planner::FindPath > 
template<>
struct MD5Sum< ::path_planner::FindPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_planner::FindPath >::value();
  }
  static const char* value(const ::path_planner::FindPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_planner::FindPathResponse> should match 
// service_traits::DataType< ::path_planner::FindPath > 
template<>
struct DataType< ::path_planner::FindPathResponse>
{
  static const char* value()
  {
    return DataType< ::path_planner::FindPath >::value();
  }
  static const char* value(const ::path_planner::FindPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_FINDPATH_H
