// Generated by gencpp from file path_planner/FindPathResponse.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_FINDPATHRESPONSE_H
#define PATH_PLANNER_MESSAGE_FINDPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planner
{
template <class ContainerAllocator>
struct FindPathResponse_
{
  typedef FindPathResponse_<ContainerAllocator> Type;

  FindPathResponse_()
    : pos_x()
    , pos_y()
    , height_agl(0.0)
    , success(false)
    , message()  {
    }
  FindPathResponse_(const ContainerAllocator& _alloc)
    : pos_x(_alloc)
    , pos_y(_alloc)
    , height_agl(0.0)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pos_x_type;
  _pos_x_type pos_x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pos_y_type;
  _pos_y_type pos_y;

   typedef float _height_agl_type;
  _height_agl_type height_agl;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::path_planner::FindPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::FindPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindPathResponse_

typedef ::path_planner::FindPathResponse_<std::allocator<void> > FindPathResponse;

typedef boost::shared_ptr< ::path_planner::FindPathResponse > FindPathResponsePtr;
typedef boost::shared_ptr< ::path_planner::FindPathResponse const> FindPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::FindPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::FindPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::FindPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::FindPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::FindPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::FindPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::FindPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::FindPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::FindPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "347017d3664ecf5abcf70677e0f54546";
  }

  static const char* value(const ::path_planner::FindPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x347017d3664ecf5aULL;
  static const uint64_t static_value2 = 0xbcf70677e0f54546ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::FindPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/FindPathResponse";
  }

  static const char* value(const ::path_planner::FindPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::FindPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] pos_x\n\
float32[] pos_y\n\
float32 height_agl\n\
bool success\n\
string message\n\
\n\
";
  }

  static const char* value(const ::path_planner::FindPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::FindPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.height_agl);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::FindPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::FindPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "pos_x[]" << std::endl;
    for (size_t i = 0; i < v.pos_x.size(); ++i)
    {
      s << indent << "  pos_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos_x[i]);
    }
    s << indent << "pos_y[]" << std::endl;
    for (size_t i = 0; i < v.pos_y.size(); ++i)
    {
      s << indent << "  pos_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos_y[i]);
    }
    s << indent << "height_agl: ";
    Printer<float>::stream(s, indent + "  ", v.height_agl);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_FINDPATHRESPONSE_H
