// Generated by gencpp from file navigation/GlobalSetpoint.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GLOBALSETPOINT_H
#define NAVIGATION_MESSAGE_GLOBALSETPOINT_H

#include <ros/service_traits.h>


#include <navigation/GlobalSetpointRequest.h>
#include <navigation/GlobalSetpointResponse.h>


namespace navigation
{

struct GlobalSetpoint
{

typedef GlobalSetpointRequest Request;
typedef GlobalSetpointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlobalSetpoint
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::GlobalSetpoint > {
  static const char* value()
  {
    return "84e486425bbf35fea76b0e2acc4e452e";
  }

  static const char* value(const ::navigation::GlobalSetpoint&) { return value(); }
};

template<>
struct DataType< ::navigation::GlobalSetpoint > {
  static const char* value()
  {
    return "navigation/GlobalSetpoint";
  }

  static const char* value(const ::navigation::GlobalSetpoint&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::GlobalSetpointRequest> should match 
// service_traits::MD5Sum< ::navigation::GlobalSetpoint > 
template<>
struct MD5Sum< ::navigation::GlobalSetpointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GlobalSetpoint >::value();
  }
  static const char* value(const ::navigation::GlobalSetpointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GlobalSetpointRequest> should match 
// service_traits::DataType< ::navigation::GlobalSetpoint > 
template<>
struct DataType< ::navigation::GlobalSetpointRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::GlobalSetpoint >::value();
  }
  static const char* value(const ::navigation::GlobalSetpointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::GlobalSetpointResponse> should match 
// service_traits::MD5Sum< ::navigation::GlobalSetpoint > 
template<>
struct MD5Sum< ::navigation::GlobalSetpointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::GlobalSetpoint >::value();
  }
  static const char* value(const ::navigation::GlobalSetpointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::GlobalSetpointResponse> should match 
// service_traits::DataType< ::navigation::GlobalSetpoint > 
template<>
struct DataType< ::navigation::GlobalSetpointResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::GlobalSetpoint >::value();
  }
  static const char* value(const ::navigation::GlobalSetpointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_GLOBALSETPOINT_H
