// Generated by gencpp from file navigation/global_setpoint.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_GLOBAL_SETPOINT_H
#define NAVIGATION_MESSAGE_GLOBAL_SETPOINT_H

#include <ros/service_traits.h>


#include <navigation/global_setpointRequest.h>
#include <navigation/global_setpointResponse.h>


namespace navigation
{

struct global_setpoint
{

typedef global_setpointRequest Request;
typedef global_setpointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct global_setpoint
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::global_setpoint > {
  static const char* value()
  {
    return "84e486425bbf35fea76b0e2acc4e452e";
  }

  static const char* value(const ::navigation::global_setpoint&) { return value(); }
};

template<>
struct DataType< ::navigation::global_setpoint > {
  static const char* value()
  {
    return "navigation/global_setpoint";
  }

  static const char* value(const ::navigation::global_setpoint&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::global_setpointRequest> should match 
// service_traits::MD5Sum< ::navigation::global_setpoint > 
template<>
struct MD5Sum< ::navigation::global_setpointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::global_setpoint >::value();
  }
  static const char* value(const ::navigation::global_setpointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::global_setpointRequest> should match 
// service_traits::DataType< ::navigation::global_setpoint > 
template<>
struct DataType< ::navigation::global_setpointRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::global_setpoint >::value();
  }
  static const char* value(const ::navigation::global_setpointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::global_setpointResponse> should match 
// service_traits::MD5Sum< ::navigation::global_setpoint > 
template<>
struct MD5Sum< ::navigation::global_setpointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::global_setpoint >::value();
  }
  static const char* value(const ::navigation::global_setpointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::global_setpointResponse> should match 
// service_traits::DataType< ::navigation::global_setpoint > 
template<>
struct DataType< ::navigation::global_setpointResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::global_setpoint >::value();
  }
  static const char* value(const ::navigation::global_setpointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_GLOBAL_SETPOINT_H
