// Generated by gencpp from file navigation/MissionWaypoints.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_MISSIONWAYPOINTS_H
#define NAVIGATION_MESSAGE_MISSIONWAYPOINTS_H

#include <ros/service_traits.h>


#include <navigation/MissionWaypointsRequest.h>
#include <navigation/MissionWaypointsResponse.h>


namespace navigation
{

struct MissionWaypoints
{

typedef MissionWaypointsRequest Request;
typedef MissionWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWaypoints
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::MissionWaypoints > {
  static const char* value()
  {
    return "6817029e547d21fe2ace732a69b3a95f";
  }

  static const char* value(const ::navigation::MissionWaypoints&) { return value(); }
};

template<>
struct DataType< ::navigation::MissionWaypoints > {
  static const char* value()
  {
    return "navigation/MissionWaypoints";
  }

  static const char* value(const ::navigation::MissionWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::MissionWaypointsRequest> should match 
// service_traits::MD5Sum< ::navigation::MissionWaypoints > 
template<>
struct MD5Sum< ::navigation::MissionWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::MissionWaypoints >::value();
  }
  static const char* value(const ::navigation::MissionWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::MissionWaypointsRequest> should match 
// service_traits::DataType< ::navigation::MissionWaypoints > 
template<>
struct DataType< ::navigation::MissionWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::MissionWaypoints >::value();
  }
  static const char* value(const ::navigation::MissionWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::MissionWaypointsResponse> should match 
// service_traits::MD5Sum< ::navigation::MissionWaypoints > 
template<>
struct MD5Sum< ::navigation::MissionWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::MissionWaypoints >::value();
  }
  static const char* value(const ::navigation::MissionWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::MissionWaypointsResponse> should match 
// service_traits::DataType< ::navigation::MissionWaypoints > 
template<>
struct DataType< ::navigation::MissionWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::MissionWaypoints >::value();
  }
  static const char* value(const ::navigation::MissionWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_MISSIONWAYPOINTS_H
