// Generated by gencpp from file commander/CANCEL_OBS_CAPTURE.msg
// DO NOT EDIT!


#ifndef COMMANDER_MESSAGE_CANCEL_OBS_CAPTURE_H
#define COMMANDER_MESSAGE_CANCEL_OBS_CAPTURE_H

#include <ros/service_traits.h>


#include <commander/CANCEL_OBS_CAPTURERequest.h>
#include <commander/CANCEL_OBS_CAPTUREResponse.h>


namespace commander
{

struct CANCEL_OBS_CAPTURE
{

typedef CANCEL_OBS_CAPTURERequest Request;
typedef CANCEL_OBS_CAPTUREResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CANCEL_OBS_CAPTURE
} // namespace commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commander::CANCEL_OBS_CAPTURE > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::commander::CANCEL_OBS_CAPTURE&) { return value(); }
};

template<>
struct DataType< ::commander::CANCEL_OBS_CAPTURE > {
  static const char* value()
  {
    return "commander/CANCEL_OBS_CAPTURE";
  }

  static const char* value(const ::commander::CANCEL_OBS_CAPTURE&) { return value(); }
};


// service_traits::MD5Sum< ::commander::CANCEL_OBS_CAPTURERequest> should match 
// service_traits::MD5Sum< ::commander::CANCEL_OBS_CAPTURE > 
template<>
struct MD5Sum< ::commander::CANCEL_OBS_CAPTURERequest>
{
  static const char* value()
  {
    return MD5Sum< ::commander::CANCEL_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::CANCEL_OBS_CAPTURERequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commander::CANCEL_OBS_CAPTURERequest> should match 
// service_traits::DataType< ::commander::CANCEL_OBS_CAPTURE > 
template<>
struct DataType< ::commander::CANCEL_OBS_CAPTURERequest>
{
  static const char* value()
  {
    return DataType< ::commander::CANCEL_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::CANCEL_OBS_CAPTURERequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commander::CANCEL_OBS_CAPTUREResponse> should match 
// service_traits::MD5Sum< ::commander::CANCEL_OBS_CAPTURE > 
template<>
struct MD5Sum< ::commander::CANCEL_OBS_CAPTUREResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commander::CANCEL_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::CANCEL_OBS_CAPTUREResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commander::CANCEL_OBS_CAPTUREResponse> should match 
// service_traits::DataType< ::commander::CANCEL_OBS_CAPTURE > 
template<>
struct DataType< ::commander::CANCEL_OBS_CAPTUREResponse>
{
  static const char* value()
  {
    return DataType< ::commander::CANCEL_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::CANCEL_OBS_CAPTUREResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMANDER_MESSAGE_CANCEL_OBS_CAPTURE_H
