// Generated by gencpp from file commander/STOP_OBS_CAPTUREResponse.msg
// DO NOT EDIT!


#ifndef COMMANDER_MESSAGE_STOP_OBS_CAPTURERESPONSE_H
#define COMMANDER_MESSAGE_STOP_OBS_CAPTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commander
{
template <class ContainerAllocator>
struct STOP_OBS_CAPTUREResponse_
{
  typedef STOP_OBS_CAPTUREResponse_<ContainerAllocator> Type;

  STOP_OBS_CAPTUREResponse_()
    : obs_name()
    , obs_lat()
    , obs_lng()
    , message()  {
    }
  STOP_OBS_CAPTUREResponse_(const ContainerAllocator& _alloc)
    : obs_name(_alloc)
    , obs_lat(_alloc)
    , obs_lng(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _obs_name_type;
  _obs_name_type obs_name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _obs_lat_type;
  _obs_lat_type obs_lat;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _obs_lng_type;
  _obs_lng_type obs_lng;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> const> ConstPtr;

}; // struct STOP_OBS_CAPTUREResponse_

typedef ::commander::STOP_OBS_CAPTUREResponse_<std::allocator<void> > STOP_OBS_CAPTUREResponse;

typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTUREResponse > STOP_OBS_CAPTUREResponsePtr;
typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTUREResponse const> STOP_OBS_CAPTUREResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40b6ce9c486fd44682f1445d56896283";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40b6ce9c486fd446ULL;
  static const uint64_t static_value2 = 0x82f1445d56896283ULL;
};

template<class ContainerAllocator>
struct DataType< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commander/STOP_OBS_CAPTUREResponse";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obs_name\n\
float64[] obs_lat\n\
float64[] obs_lng\n\
string message\n\
";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obs_name);
      stream.next(m.obs_lat);
      stream.next(m.obs_lng);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct STOP_OBS_CAPTUREResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commander::STOP_OBS_CAPTUREResponse_<ContainerAllocator>& v)
  {
    s << indent << "obs_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.obs_name);
    s << indent << "obs_lat[]" << std::endl;
    for (size_t i = 0; i < v.obs_lat.size(); ++i)
    {
      s << indent << "  obs_lat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.obs_lat[i]);
    }
    s << indent << "obs_lng[]" << std::endl;
    for (size_t i = 0; i < v.obs_lng.size(); ++i)
    {
      s << indent << "  obs_lng[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.obs_lng[i]);
    }
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDER_MESSAGE_STOP_OBS_CAPTURERESPONSE_H
