// Generated by gencpp from file commander/STOP_OBS_CAPTURERequest.msg
// DO NOT EDIT!


#ifndef COMMANDER_MESSAGE_STOP_OBS_CAPTUREREQUEST_H
#define COMMANDER_MESSAGE_STOP_OBS_CAPTUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commander
{
template <class ContainerAllocator>
struct STOP_OBS_CAPTURERequest_
{
  typedef STOP_OBS_CAPTURERequest_<ContainerAllocator> Type;

  STOP_OBS_CAPTURERequest_()
    {
    }
  STOP_OBS_CAPTURERequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> const> ConstPtr;

}; // struct STOP_OBS_CAPTURERequest_

typedef ::commander::STOP_OBS_CAPTURERequest_<std::allocator<void> > STOP_OBS_CAPTURERequest;

typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTURERequest > STOP_OBS_CAPTURERequestPtr;
typedef boost::shared_ptr< ::commander::STOP_OBS_CAPTURERequest const> STOP_OBS_CAPTURERequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commander/STOP_OBS_CAPTURERequest";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct STOP_OBS_CAPTURERequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::commander::STOP_OBS_CAPTURERequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDER_MESSAGE_STOP_OBS_CAPTUREREQUEST_H
