// Generated by gencpp from file commander/STOP_OBS_CAPTURE.msg
// DO NOT EDIT!


#ifndef COMMANDER_MESSAGE_STOP_OBS_CAPTURE_H
#define COMMANDER_MESSAGE_STOP_OBS_CAPTURE_H

#include <ros/service_traits.h>


#include <commander/STOP_OBS_CAPTURERequest.h>
#include <commander/STOP_OBS_CAPTUREResponse.h>


namespace commander
{

struct STOP_OBS_CAPTURE
{

typedef STOP_OBS_CAPTURERequest Request;
typedef STOP_OBS_CAPTUREResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct STOP_OBS_CAPTURE
} // namespace commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commander::STOP_OBS_CAPTURE > {
  static const char* value()
  {
    return "40b6ce9c486fd44682f1445d56896283";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTURE&) { return value(); }
};

template<>
struct DataType< ::commander::STOP_OBS_CAPTURE > {
  static const char* value()
  {
    return "commander/STOP_OBS_CAPTURE";
  }

  static const char* value(const ::commander::STOP_OBS_CAPTURE&) { return value(); }
};


// service_traits::MD5Sum< ::commander::STOP_OBS_CAPTURERequest> should match 
// service_traits::MD5Sum< ::commander::STOP_OBS_CAPTURE > 
template<>
struct MD5Sum< ::commander::STOP_OBS_CAPTURERequest>
{
  static const char* value()
  {
    return MD5Sum< ::commander::STOP_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::STOP_OBS_CAPTURERequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commander::STOP_OBS_CAPTURERequest> should match 
// service_traits::DataType< ::commander::STOP_OBS_CAPTURE > 
template<>
struct DataType< ::commander::STOP_OBS_CAPTURERequest>
{
  static const char* value()
  {
    return DataType< ::commander::STOP_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::STOP_OBS_CAPTURERequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commander::STOP_OBS_CAPTUREResponse> should match 
// service_traits::MD5Sum< ::commander::STOP_OBS_CAPTURE > 
template<>
struct MD5Sum< ::commander::STOP_OBS_CAPTUREResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commander::STOP_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::STOP_OBS_CAPTUREResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commander::STOP_OBS_CAPTUREResponse> should match 
// service_traits::DataType< ::commander::STOP_OBS_CAPTURE > 
template<>
struct DataType< ::commander::STOP_OBS_CAPTUREResponse>
{
  static const char* value()
  {
    return DataType< ::commander::STOP_OBS_CAPTURE >::value();
  }
  static const char* value(const ::commander::STOP_OBS_CAPTUREResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMANDER_MESSAGE_STOP_OBS_CAPTURE_H
