// Generated by gencpp from file map_manager/Float1DArray.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_FLOAT1DARRAY_H
#define MAP_MANAGER_MESSAGE_FLOAT1DARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_manager
{
template <class ContainerAllocator>
struct Float1DArray_
{
  typedef Float1DArray_<ContainerAllocator> Type;

  Float1DArray_()
    : single_coord()  {
    }
  Float1DArray_(const ContainerAllocator& _alloc)
    : single_coord(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _single_coord_type;
  _single_coord_type single_coord;





  typedef boost::shared_ptr< ::map_manager::Float1DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::Float1DArray_<ContainerAllocator> const> ConstPtr;

}; // struct Float1DArray_

typedef ::map_manager::Float1DArray_<std::allocator<void> > Float1DArray;

typedef boost::shared_ptr< ::map_manager::Float1DArray > Float1DArrayPtr;
typedef boost::shared_ptr< ::map_manager::Float1DArray const> Float1DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::Float1DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::Float1DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'map_manager': ['/home/darth/Desktop/sc2_ros/src/map_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::Float1DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::Float1DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::Float1DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::Float1DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::Float1DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::Float1DArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::Float1DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1426ab7ee5dd52e03f7484660624498e";
  }

  static const char* value(const ::map_manager::Float1DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1426ab7ee5dd52e0ULL;
  static const uint64_t static_value2 = 0x3f7484660624498eULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::Float1DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/Float1DArray";
  }

  static const char* value(const ::map_manager::Float1DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::Float1DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] single_coord\n\
";
  }

  static const char* value(const ::map_manager::Float1DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::Float1DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.single_coord);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float1DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::Float1DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::Float1DArray_<ContainerAllocator>& v)
  {
    s << indent << "single_coord[]" << std::endl;
    for (size_t i = 0; i < v.single_coord.size(); ++i)
    {
      s << indent << "  single_coord[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.single_coord[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_FLOAT1DARRAY_H
