// Generated by gencpp from file map_manager/GetMapList.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETMAPLIST_H
#define MAP_MANAGER_MESSAGE_GETMAPLIST_H

#include <ros/service_traits.h>


#include <map_manager/GetMapListRequest.h>
#include <map_manager/GetMapListResponse.h>


namespace map_manager
{

struct GetMapList
{

typedef GetMapListRequest Request;
typedef GetMapListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapList
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::GetMapList > {
  static const char* value()
  {
    return "fcae05604cd2e87fd94fb58351b33527";
  }

  static const char* value(const ::map_manager::GetMapList&) { return value(); }
};

template<>
struct DataType< ::map_manager::GetMapList > {
  static const char* value()
  {
    return "map_manager/GetMapList";
  }

  static const char* value(const ::map_manager::GetMapList&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::GetMapListRequest> should match 
// service_traits::MD5Sum< ::map_manager::GetMapList > 
template<>
struct MD5Sum< ::map_manager::GetMapListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetMapList >::value();
  }
  static const char* value(const ::map_manager::GetMapListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetMapListRequest> should match 
// service_traits::DataType< ::map_manager::GetMapList > 
template<>
struct DataType< ::map_manager::GetMapListRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetMapList >::value();
  }
  static const char* value(const ::map_manager::GetMapListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::GetMapListResponse> should match 
// service_traits::MD5Sum< ::map_manager::GetMapList > 
template<>
struct MD5Sum< ::map_manager::GetMapListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetMapList >::value();
  }
  static const char* value(const ::map_manager::GetMapListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetMapListResponse> should match 
// service_traits::DataType< ::map_manager::GetMapList > 
template<>
struct DataType< ::map_manager::GetMapListResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetMapList >::value();
  }
  static const char* value(const ::map_manager::GetMapListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETMAPLIST_H
