// Generated by gencpp from file map_manager/GetMapListResponse.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETMAPLISTRESPONSE_H
#define MAP_MANAGER_MESSAGE_GETMAPLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_manager
{
template <class ContainerAllocator>
struct GetMapListResponse_
{
  typedef GetMapListResponse_<ContainerAllocator> Type;

  GetMapListResponse_()
    : success(false)
    , message()
    , map_ids()  {
    }
  GetMapListResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , map_ids(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _map_ids_type;
  _map_ids_type map_ids;





  typedef boost::shared_ptr< ::map_manager::GetMapListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::GetMapListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapListResponse_

typedef ::map_manager::GetMapListResponse_<std::allocator<void> > GetMapListResponse;

typedef boost::shared_ptr< ::map_manager::GetMapListResponse > GetMapListResponsePtr;
typedef boost::shared_ptr< ::map_manager::GetMapListResponse const> GetMapListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::GetMapListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::GetMapListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'map_manager': ['/home/darth/Desktop/sc2_ros/src/map_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetMapListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetMapListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetMapListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetMapListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetMapListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetMapListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::GetMapListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcae05604cd2e87fd94fb58351b33527";
  }

  static const char* value(const ::map_manager::GetMapListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcae05604cd2e87fULL;
  static const uint64_t static_value2 = 0xd94fb58351b33527ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::GetMapListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/GetMapListResponse";
  }

  static const char* value(const ::map_manager::GetMapListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::GetMapListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string message\n\
string[] map_ids\n\
\n\
";
  }

  static const char* value(const ::map_manager::GetMapListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::GetMapListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.map_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::GetMapListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::GetMapListResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "map_ids[]" << std::endl;
    for (size_t i = 0; i < v.map_ids.size(); ++i)
    {
      s << indent << "  map_ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETMAPLISTRESPONSE_H
