// Generated by gencpp from file map_manager/GetMapInfoByName.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETMAPINFOBYNAME_H
#define MAP_MANAGER_MESSAGE_GETMAPINFOBYNAME_H

#include <ros/service_traits.h>


#include <map_manager/GetMapInfoByNameRequest.h>
#include <map_manager/GetMapInfoByNameResponse.h>


namespace map_manager
{

struct GetMapInfoByName
{

typedef GetMapInfoByNameRequest Request;
typedef GetMapInfoByNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapInfoByName
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::GetMapInfoByName > {
  static const char* value()
  {
    return "9853cd9476867110697e3e2277194759";
  }

  static const char* value(const ::map_manager::GetMapInfoByName&) { return value(); }
};

template<>
struct DataType< ::map_manager::GetMapInfoByName > {
  static const char* value()
  {
    return "map_manager/GetMapInfoByName";
  }

  static const char* value(const ::map_manager::GetMapInfoByName&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::GetMapInfoByNameRequest> should match 
// service_traits::MD5Sum< ::map_manager::GetMapInfoByName > 
template<>
struct MD5Sum< ::map_manager::GetMapInfoByNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetMapInfoByName >::value();
  }
  static const char* value(const ::map_manager::GetMapInfoByNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetMapInfoByNameRequest> should match 
// service_traits::DataType< ::map_manager::GetMapInfoByName > 
template<>
struct DataType< ::map_manager::GetMapInfoByNameRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetMapInfoByName >::value();
  }
  static const char* value(const ::map_manager::GetMapInfoByNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::GetMapInfoByNameResponse> should match 
// service_traits::MD5Sum< ::map_manager::GetMapInfoByName > 
template<>
struct MD5Sum< ::map_manager::GetMapInfoByNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetMapInfoByName >::value();
  }
  static const char* value(const ::map_manager::GetMapInfoByNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetMapInfoByNameResponse> should match 
// service_traits::DataType< ::map_manager::GetMapInfoByName > 
template<>
struct DataType< ::map_manager::GetMapInfoByNameResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetMapInfoByName >::value();
  }
  static const char* value(const ::map_manager::GetMapInfoByNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETMAPINFOBYNAME_H
