// Generated by gencpp from file map_manager/GetObstacles.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETOBSTACLES_H
#define MAP_MANAGER_MESSAGE_GETOBSTACLES_H

#include <ros/service_traits.h>


#include <map_manager/GetObstaclesRequest.h>
#include <map_manager/GetObstaclesResponse.h>


namespace map_manager
{

struct GetObstacles
{

typedef GetObstaclesRequest Request;
typedef GetObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObstacles
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::GetObstacles > {
  static const char* value()
  {
    return "463fe8e4f9b2a4671162d1724d05221c";
  }

  static const char* value(const ::map_manager::GetObstacles&) { return value(); }
};

template<>
struct DataType< ::map_manager::GetObstacles > {
  static const char* value()
  {
    return "map_manager/GetObstacles";
  }

  static const char* value(const ::map_manager::GetObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::GetObstaclesRequest> should match 
// service_traits::MD5Sum< ::map_manager::GetObstacles > 
template<>
struct MD5Sum< ::map_manager::GetObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetObstacles >::value();
  }
  static const char* value(const ::map_manager::GetObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetObstaclesRequest> should match 
// service_traits::DataType< ::map_manager::GetObstacles > 
template<>
struct DataType< ::map_manager::GetObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetObstacles >::value();
  }
  static const char* value(const ::map_manager::GetObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::GetObstaclesResponse> should match 
// service_traits::MD5Sum< ::map_manager::GetObstacles > 
template<>
struct MD5Sum< ::map_manager::GetObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetObstacles >::value();
  }
  static const char* value(const ::map_manager::GetObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetObstaclesResponse> should match 
// service_traits::DataType< ::map_manager::GetObstacles > 
template<>
struct DataType< ::map_manager::GetObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetObstacles >::value();
  }
  static const char* value(const ::map_manager::GetObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETOBSTACLES_H
