// Generated by gencpp from file map_manager/GetObstaclesResponse.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETOBSTACLESRESPONSE_H
#define MAP_MANAGER_MESSAGE_GETOBSTACLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <map_manager/Float1DArray.h>
#include <map_manager/Float1DArray.h>

namespace map_manager
{
template <class ContainerAllocator>
struct GetObstaclesResponse_
{
  typedef GetObstaclesResponse_<ContainerAllocator> Type;

  GetObstaclesResponse_()
    : success(false)
    , message()
    , obstacle_ids()
    , lngs()
    , lats()  {
    }
  GetObstaclesResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , obstacle_ids(_alloc)
    , lngs(_alloc)
    , lats(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _obstacle_ids_type;
  _obstacle_ids_type obstacle_ids;

   typedef std::vector< ::map_manager::Float1DArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::map_manager::Float1DArray_<ContainerAllocator> >::other >  _lngs_type;
  _lngs_type lngs;

   typedef std::vector< ::map_manager::Float1DArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::map_manager::Float1DArray_<ContainerAllocator> >::other >  _lats_type;
  _lats_type lats;





  typedef boost::shared_ptr< ::map_manager::GetObstaclesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::GetObstaclesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetObstaclesResponse_

typedef ::map_manager::GetObstaclesResponse_<std::allocator<void> > GetObstaclesResponse;

typedef boost::shared_ptr< ::map_manager::GetObstaclesResponse > GetObstaclesResponsePtr;
typedef boost::shared_ptr< ::map_manager::GetObstaclesResponse const> GetObstaclesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::GetObstaclesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'map_manager': ['/home/darth/Desktop/sc2_ros/src/map_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetObstaclesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetObstaclesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetObstaclesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9136b55f13373feef71438708fce2471";
  }

  static const char* value(const ::map_manager::GetObstaclesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9136b55f13373feeULL;
  static const uint64_t static_value2 = 0xf71438708fce2471ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/GetObstaclesResponse";
  }

  static const char* value(const ::map_manager::GetObstaclesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string message\n\
string[] obstacle_ids\n\
Float1DArray[] lngs\n\
Float1DArray[] lats\n\
\n\
\n\
================================================================================\n\
MSG: map_manager/Float1DArray\n\
float32[] single_coord\n\
";
  }

  static const char* value(const ::map_manager::GetObstaclesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.obstacle_ids);
      stream.next(m.lngs);
      stream.next(m.lats);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObstaclesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::GetObstaclesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::GetObstaclesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "obstacle_ids[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_ids.size(); ++i)
    {
      s << indent << "  obstacle_ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.obstacle_ids[i]);
    }
    s << indent << "lngs[]" << std::endl;
    for (size_t i = 0; i < v.lngs.size(); ++i)
    {
      s << indent << "  lngs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::map_manager::Float1DArray_<ContainerAllocator> >::stream(s, indent + "    ", v.lngs[i]);
    }
    s << indent << "lats[]" << std::endl;
    for (size_t i = 0; i < v.lats.size(); ++i)
    {
      s << indent << "  lats[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::map_manager::Float1DArray_<ContainerAllocator> >::stream(s, indent + "    ", v.lats[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETOBSTACLESRESPONSE_H
