// Generated by gencpp from file map_manager/SaveObstacles.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_SAVEOBSTACLES_H
#define MAP_MANAGER_MESSAGE_SAVEOBSTACLES_H

#include <ros/service_traits.h>


#include <map_manager/SaveObstaclesRequest.h>
#include <map_manager/SaveObstaclesResponse.h>


namespace map_manager
{

struct SaveObstacles
{

typedef SaveObstaclesRequest Request;
typedef SaveObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveObstacles
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::SaveObstacles > {
  static const char* value()
  {
    return "abd0dab24fc4e5b35491883975867c94";
  }

  static const char* value(const ::map_manager::SaveObstacles&) { return value(); }
};

template<>
struct DataType< ::map_manager::SaveObstacles > {
  static const char* value()
  {
    return "map_manager/SaveObstacles";
  }

  static const char* value(const ::map_manager::SaveObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::SaveObstaclesRequest> should match 
// service_traits::MD5Sum< ::map_manager::SaveObstacles > 
template<>
struct MD5Sum< ::map_manager::SaveObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::SaveObstacles >::value();
  }
  static const char* value(const ::map_manager::SaveObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::SaveObstaclesRequest> should match 
// service_traits::DataType< ::map_manager::SaveObstacles > 
template<>
struct DataType< ::map_manager::SaveObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::SaveObstacles >::value();
  }
  static const char* value(const ::map_manager::SaveObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::SaveObstaclesResponse> should match 
// service_traits::MD5Sum< ::map_manager::SaveObstacles > 
template<>
struct MD5Sum< ::map_manager::SaveObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::SaveObstacles >::value();
  }
  static const char* value(const ::map_manager::SaveObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::SaveObstaclesResponse> should match 
// service_traits::DataType< ::map_manager::SaveObstacles > 
template<>
struct DataType< ::map_manager::SaveObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::SaveObstacles >::value();
  }
  static const char* value(const ::map_manager::SaveObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_SAVEOBSTACLES_H
