// Generated by gencpp from file map_manager/SaveMapRequest.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_SAVEMAPREQUEST_H
#define MAP_MANAGER_MESSAGE_SAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_manager
{
template <class ContainerAllocator>
struct SaveMapRequest_
{
  typedef SaveMapRequest_<ContainerAllocator> Type;

  SaveMapRequest_()
    : map_id()
    , height_agl(0.0)
    , lng()
    , lat()  {
    }
  SaveMapRequest_(const ContainerAllocator& _alloc)
    : map_id(_alloc)
    , height_agl(0.0)
    , lng(_alloc)
    , lat(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_id_type;
  _map_id_type map_id;

   typedef float _height_agl_type;
  _height_agl_type height_agl;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lng_type;
  _lng_type lng;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _lat_type;
  _lat_type lat;





  typedef boost::shared_ptr< ::map_manager::SaveMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::SaveMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapRequest_

typedef ::map_manager::SaveMapRequest_<std::allocator<void> > SaveMapRequest;

typedef boost::shared_ptr< ::map_manager::SaveMapRequest > SaveMapRequestPtr;
typedef boost::shared_ptr< ::map_manager::SaveMapRequest const> SaveMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::SaveMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::SaveMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'map_manager': ['/home/darth/Desktop/sc2_ros/src/map_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::SaveMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::SaveMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "585ab74f8f195546a3c33d376967fa2a";
  }

  static const char* value(const ::map_manager::SaveMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x585ab74f8f195546ULL;
  static const uint64_t static_value2 = 0xa3c33d376967fa2aULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/SaveMapRequest";
  }

  static const char* value(const ::map_manager::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_id\n\
float32 height_agl\n\
float32[] lng\n\
float32[] lat\n\
";
  }

  static const char* value(const ::map_manager::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::SaveMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_id);
      stream.next(m.height_agl);
      stream.next(m.lng);
      stream.next(m.lat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::SaveMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::SaveMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_id);
    s << indent << "height_agl: ";
    Printer<float>::stream(s, indent + "  ", v.height_agl);
    s << indent << "lng[]" << std::endl;
    for (size_t i = 0; i < v.lng.size(); ++i)
    {
      s << indent << "  lng[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lng[i]);
    }
    s << indent << "lat[]" << std::endl;
    for (size_t i = 0; i < v.lat.size(); ++i)
    {
      s << indent << "  lat[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lat[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_SAVEMAPREQUEST_H
