// Generated by gencpp from file map_manager/SaveMap.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_SAVEMAP_H
#define MAP_MANAGER_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <map_manager/SaveMapRequest.h>
#include <map_manager/SaveMapResponse.h>


namespace map_manager
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::SaveMap > {
  static const char* value()
  {
    return "19e2ab991a9960cc2be2f5217abb7783";
  }

  static const char* value(const ::map_manager::SaveMap&) { return value(); }
};

template<>
struct DataType< ::map_manager::SaveMap > {
  static const char* value()
  {
    return "map_manager/SaveMap";
  }

  static const char* value(const ::map_manager::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::SaveMapRequest> should match 
// service_traits::MD5Sum< ::map_manager::SaveMap > 
template<>
struct MD5Sum< ::map_manager::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::SaveMap >::value();
  }
  static const char* value(const ::map_manager::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::SaveMapRequest> should match 
// service_traits::DataType< ::map_manager::SaveMap > 
template<>
struct DataType< ::map_manager::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::SaveMap >::value();
  }
  static const char* value(const ::map_manager::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::SaveMapResponse> should match 
// service_traits::MD5Sum< ::map_manager::SaveMap > 
template<>
struct MD5Sum< ::map_manager::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::SaveMap >::value();
  }
  static const char* value(const ::map_manager::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::SaveMapResponse> should match 
// service_traits::DataType< ::map_manager::SaveMap > 
template<>
struct DataType< ::map_manager::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::SaveMap >::value();
  }
  static const char* value(const ::map_manager::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_SAVEMAP_H
