// Generated by gencpp from file map_manager/StartMission.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_STARTMISSION_H
#define MAP_MANAGER_MESSAGE_STARTMISSION_H

#include <ros/service_traits.h>


#include <map_manager/StartMissionRequest.h>
#include <map_manager/StartMissionResponse.h>


namespace map_manager
{

struct StartMission
{

typedef StartMissionRequest Request;
typedef StartMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartMission
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::StartMission > {
  static const char* value()
  {
    return "55f40e5bb59a86c5c866c1e3dc5d2ad5";
  }

  static const char* value(const ::map_manager::StartMission&) { return value(); }
};

template<>
struct DataType< ::map_manager::StartMission > {
  static const char* value()
  {
    return "map_manager/StartMission";
  }

  static const char* value(const ::map_manager::StartMission&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::StartMissionRequest> should match 
// service_traits::MD5Sum< ::map_manager::StartMission > 
template<>
struct MD5Sum< ::map_manager::StartMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::StartMission >::value();
  }
  static const char* value(const ::map_manager::StartMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::StartMissionRequest> should match 
// service_traits::DataType< ::map_manager::StartMission > 
template<>
struct DataType< ::map_manager::StartMissionRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::StartMission >::value();
  }
  static const char* value(const ::map_manager::StartMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::StartMissionResponse> should match 
// service_traits::MD5Sum< ::map_manager::StartMission > 
template<>
struct MD5Sum< ::map_manager::StartMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::StartMission >::value();
  }
  static const char* value(const ::map_manager::StartMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::StartMissionResponse> should match 
// service_traits::DataType< ::map_manager::StartMission > 
template<>
struct DataType< ::map_manager::StartMissionResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::StartMission >::value();
  }
  static const char* value(const ::map_manager::StartMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_STARTMISSION_H
