(cl:defpackage navigation-srv
  (:use )
  (:export
   "GLOBALSETPOINT"
   "<GLOBALSETPOINT-REQUEST>"
   "GLOBALSETPOINT-REQUEST"
   "<GLOBALSETPOINT-RESPONSE>"
   "GLOBALSETPOINT-RESPONSE"
   "MISSIONWAYPOINTS"
   "<MISSIONWAYPOINTS-REQUEST>"
   "MISSIONWAYPOINTS-REQUEST"
   "<MISSIONWAYPOINTS-RESPONSE>"
   "MISSIONWAYPOINTS-RESPONSE"
   "GLOBAL_SETPOINT"
   "<GLOBAL_SETPOINT-REQUEST>"
   "GLOBAL_SETPOINT-REQUEST"
   "<GLOBAL_SETPOINT-RESPONSE>"
   "GLOBAL_SETPOINT-RESPONSE"
  ))

